### ISSUE TITLE
not idempotent when updating from build.gradle if the toml version uses a versions.ref requires

### ISSUE THREAD

**Issue by RBusarow** [RBusarow/gradle-dependency-sync#61]
This is a common use-case with Dependabot, which will often only update a single artifact version (such as `lib-api` but not `lib-runtime`) per PR.

given: 

```kotlin
// build.gradle.kts
dependencies {
  dependencysync("com.foo.lib:lib-api:0.0.2") // this was just updated
  dependencysync("com.foo.lib:lib-runtime:0.0.1")
}
```

```toml
// libs.versions.toml
[versions]
foo-lib = "0.0.1"

[libs]
foo-lib-api = { module = "com.foo.lib:lib-api", version.ref = "foo-lib" }
foo-lib-runtime = { module = "com.foo.lib:lib-runtime", version.ref = "foo-lib" }
```

If Dependabot makes a PR with these two files, running `./gradlew dependencysync` once will result in the `toml` file getting updated, but the build file will still have `lib-runtime` at `0.0.1`.  If `./gradlew dependencysync` runs a second time, the remaining dependency will be updated based upon the toml file's version.

### expected behavior

The task should only need to run once in order to apply all changes.  Running the task again should not generate any changes.
